forgehax.version=${forgehax_version}
forgehax.mc.version=${forgehax_mc_version}
forgehax.forge.version=${forgehax_forge_version}
forgehax.mcp.version=${forgehax_mcp_version}
forgehax.mcp.channel=${forgehax_mcp_channel}
forgehax.mcp.mapping=${forgehax_mcp_mapping}
